#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_DIR="$ROOT_DIR/local"
ENV_FILE="$LOCAL_DIR/.env"
COMPOSE_FILE="$LOCAL_DIR/docker-compose.yml"

print() { printf "%s\n" "$*"; }
err() { printf "ERROR: %s\n" "$*" >&2; }

check_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "required command not found: $1"
    return 1
  fi
}

ensure_docker() {
  check_cmd docker || exit 1
  if ! docker info >/dev/null 2>&1; then
    err "docker daemon doesn't seem to be running or you lack permissions."
    exit 1
  fi
}

ask() {
  local prompt="$1" default="$2"
  if [ -n "${SKIP_PROMPTS-}" ]; then
    printf "%s" "$default"
    return
  fi
  if [ -n "$default" ]; then
    read -r -p "$prompt [$default]: " val
    if [ -z "$val" ]; then val="$default"; fi
  else
    read -r -p "$prompt: " val
  fi
  printf "%s" "$val"
}

usage() {
  cat <<EOF
Usage: $0 [--yes] [--domain DOMAIN] [--admin EMAIL] [--mailpit|--kumomta]

--yes       : non-interactive, accept defaults
--domain    : domain to serve Reloop on (e.g. reloop.example.com)
--admin     : admin email for initial account
--mailpit   : use Mailpit for SMTP (default)
--kumomta   : use KumoMTA instead of Mailpit
EOF
}

# parse args
DOMAIN=""
ADMIN_EMAIL=""
USE_MAILPIT=1
NONINTERACTIVE=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --yes) NONINTERACTIVE=1; SKIP_PROMPTS=1; shift ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    --admin) ADMIN_EMAIL="$2"; shift 2 ;;
    --mailpit) USE_MAILPIT=1; shift ;;
    --kumomta) USE_MAILPIT=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) err "unknown arg: $1"; usage; exit 1 ;;
  esac
done

if [ "$NONINTERACTIVE" -eq 1 ]; then SKIP_PROMPTS=1; fi

if [ -z "$DOMAIN" ]; then
  DOMAIN=$(ask "Domain to serve Reloop on (use local.dev for local)" "reloop.local")
fi
if [ -z "$ADMIN_EMAIL" ]; then
  ADMIN_EMAIL=$(ask "Admin email for initial account" "admin@${DOMAIN}")
fi

ensure_docker

mkdir -p "$LOCAL_DIR"

cat > "$ENV_FILE" <<EOF
# Auto-generated by local/onboarding.sh
DOMAIN=${DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
USE_MAILPIT=${USE_MAILPIT}
# Default SMTP settings for Mailpit
SMTP_HOST=localhost
SMTP_PORT=1025
# Default DB credentials (override if you want)
POSTGRES_USER=reloop
POSTGRES_PASSWORD=reloop123
POSTGRES_DB=reloop
EOF

print "Wrote $ENV_FILE"

if [ ! -f "$COMPOSE_FILE" ]; then
  err "local/docker-compose.yml not found. Please create or copy the repo's local/docker-compose.yml into $COMPOSE_FILE"
  exit 1
fi

print "Pulling docker images (may take a few minutes)..."

docker compose -f "$COMPOSE_FILE" pull || true

print "Starting services with docker compose..."
docker compose -f "$COMPOSE_FILE" up -d

print "Waiting for core services to be healthy..."
wait_for_port() {
  local host=${1:-localhost}
  local port=${2}
  local retries=60
  local i=0
  while ! (echo >/dev/tcp/${host}/${port}) >/dev/null 2>&1; do
    i=$((i+1))
    if [ $i -ge $retries ]; then
      err "timeout waiting for ${host}:${port}"
      return 1
    fi
    sleep 1
  done
  return 0
}

if wait_for_port localhost 8000; then
  print "Backend reachable on localhost:8000"
else
  print "Backend not yet reachable; continue and check logs."
fi

if [ "$USE_MAILPIT" -eq 1 ]; then
  if wait_for_port localhost 8025; then
    print "Mailpit UI reachable on http://localhost:8025"
  else
    print "Mailpit not yet reachable."
  fi
fi

print "Done."
print "To follow logs: docker compose -f local/docker-compose.yml logs -f"
print "To open dashboard: https://${DOMAIN} (or http://localhost:3000 for local dev)"

exit 0
