export const TEMPLATE_ERROR_CODES = {
	TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
	TEMPLATE_NAME_REQUIRED: "TEMPLATE_NAME_REQUIRED",
	TEMPLATE_CONTENT_INVALID: "TEMPLATE_CONTENT_INVALID",
	TEMPLATE_ALREADY_EXISTS: "TEMPLATE_ALREADY_EXISTS",
	TEMPLATE_PUBLISH_FAILED: "TEMPLATE_PUBLISH_FAILED",
	TEMPLATE_DELETE_FAILED: "TEMPLATE_DELETE_FAILED",
	TEMPLATE_RENDER_FAILED: "TEMPLATE_RENDER_FAILED",
	TEMPLATE_VERSION_NOT_FOUND: "TEMPLATE_VERSION_NOT_FOUND",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type TemplateErrorCode =
	(typeof TEMPLATE_ERROR_CODES)[keyof typeof TEMPLATE_ERROR_CODES];
