export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	DOMAIN_ALREADY_EXISTS: "DOMAIN_ALREADY_EXISTS",
	DOMAIN_NOT_FOUND: "DOMAIN_NOT_FOUND",
	DOMAIN_INVALID: "DOMAIN_INVALID",
	DOMAIN_UNAUTHORIZED: "DOMAIN_UNAUTHORIZED",
	DOMAIN_FORBIDDEN: "DOMAIN_FORBIDDEN",
	DOMAIN_BAD_REQUEST: "DOMAIN_BAD_REQUEST",
	DOMAIN_INTERNAL_SERVER_ERROR: "DOMAIN_INTERNAL_SERVER_ERROR",
} as const;
