apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://reloop-clickhouse:8123
    database: reloop_analytics
    user: reloop
    secureJsonData:
      password: reloop123
    jsonData:
      defaultDatabase: reloop_analytics
      port: 9000
      server: reloop-clickhouse
      username: reloop
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://reloop-otel-collector:8889
    isDefault: false
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://reloop-loki:3100
    isDefault: false
    editable: true
