export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

	CONTACT_ALREADY_EXISTS: "CONTACT_ALREADY_EXISTS",
	CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",
	INVALID_EMAIL: "INVALID_EMAIL",
	DATABASE_ERROR: "DATABASE_ERROR",

	GROUP_ALREADY_EXISTS: "GROUP_ALREADY_EXISTS",
	GROUP_NOT_FOUND: "GROUP_NOT_FOUND",

	PROPERTY_ALREADY_EXISTS: "PROPERTY_ALREADY_EXISTS",
	PROPERTY_NOT_FOUND: "PROPERTY_NOT_FOUND",

	CHANNEL_ALREADY_EXISTS: "CHANNEL_ALREADY_EXISTS",
	CHANNEL_NOT_FOUND: "CHANNEL_NOT_FOUND",

	SUBSCRIPTION_ALREADY_EXISTS: "SUBSCRIPTION_ALREADY_EXISTS",
	SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",

	PREFERENCE_ALREADY_EXISTS: "PREFERENCE_ALREADY_EXISTS",
	PREFERENCE_NOT_FOUND: "PREFERENCE_NOT_FOUND",
} as const;
