export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

	CONTACT_ALREADY_EXISTS: "CONTACT_ALREADY_EXISTS",
	CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",
	INVALID_EMAIL: "INVALID_EMAIL",
	DATABASE_ERROR: "DATABASE_ERROR",
} as const;
