FROM oven/bun:alpine AS base

# Stage 1: Install dependencies
FROM base AS deps
WORKDIR /app
COPY . .
RUN bun install --frozen-lockfile

# Stage 2: Build the application
FROM base AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run --filter=docs build

# Stage 3: Production server
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/frontend/docs/public ./docs/public
COPY --from=builder /app/apps/frontend/docs/.next ./docs/.next
COPY --from=deps /app/node_modules ./docs/node_modules
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/frontend/docs/package.json ./docs/package.json

EXPOSE 3000
CMD ["bun", "--cwd","docs" ,"start"]
