// AUTO-GENERATED by apps/frontend/docs/scripts/sync-dashboard-api-key-samples.ts
// Do not edit by hand.
// Canonical source: apps/backend/api-key route x-codeSamples.ts files
// Regenerate: cd apps/frontend/docs && bun run sync:sdk-samples

export const codeExamples = {
	javascript: {
		create: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.create({
  name: "Production Key",
});

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.key);`,
		list: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKeys, apiKeyError } = await reloop.apiKey.list({
  page: 1,
  limit: 10,
  enabled: true,
});

if (apiKeyError) throw apiKeyError;

console.log(apiKeys.total, apiKeys.apiKeys);`,
		rotate: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.rotate("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.key);`,
		disable: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.disable("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.enabled);`,
	},
	python: {
		create: `from reloop import Reloop

reloop = Reloop(api_key="rl_123456789")

api_key = reloop.api_keys.create(name="Production Key")`,
		list: `from reloop import Reloop

reloop = Reloop(api_key="rl_123456789")

api_keys = reloop.api_keys.list(page=1, limit=10)`,
		rotate: `from reloop import Reloop

reloop = Reloop(api_key="rl_123456789")

reloop.api_keys.rotate("key_123456789")`,
		disable: `from reloop import Reloop

reloop = Reloop(api_key="rl_123456789")

reloop.api_keys.disable("key_123456789")`,
	},
	php: {
		create: `$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKeys->create(['name' => 'Production Key']);`,
		list: `$reloop = Reloop::client('rl_123456789');

$apiKeys = $reloop->apiKeys->list(['page' => 1, 'limit' => 10]);`,
		rotate: `$reloop = Reloop::client('rl_123456789');

$reloop->apiKeys->rotate('key_123456789');`,
		disable: `$reloop = Reloop::client('rl_123456789');

$reloop->apiKeys->disable('key_123456789');`,
	},
};
