// AUTO-GENERATED by scripts/sync-dashboard-api-key-samples.ts
// Do not edit by hand.
// Canonical source: packages/code-samples (@reloop/code-samples)
// Regenerate: bun run sync:sdk-samples

export const languages = [
	{ id: "nodejs", label: "Node", shikiLang: "javascript" },
	{ id: "python", label: "Python", shikiLang: "python" },
	{ id: "php", label: "PHP", shikiLang: "php" },
	{ id: "java", label: "Java", shikiLang: "java" },
] as const;

export const operations = [
	{
		id: "create",
		label: "Create Key",
		method: "POST",
		endpoint: "/api/api-key/v1/",
		docSlug: "post-api-api-key-v1",
	},
	{
		id: "list",
		label: "List Keys",
		method: "GET",
		endpoint: "/api/api-key/v1/",
		docSlug: "get-api-api-key-v1",
	},
	{
		id: "get",
		label: "Get Key",
		method: "GET",
		endpoint: "/api/api-key/v1/:id",
		docSlug: "get-api-api-key-v1by-api_key_id",
	},
	{
		id: "update",
		label: "Update Key",
		method: "PATCH",
		endpoint: "/api/api-key/v1/:id",
		docSlug: "patch-api-api-key-v1by-api_key_id",
	},
	{
		id: "delete",
		label: "Delete Key",
		method: "DELETE",
		endpoint: "/api/api-key/v1/:id",
		docSlug: "delete-api-api-key-v1by-api_key_id",
	},
	{
		id: "rotate",
		label: "Rotate Key",
		method: "POST",
		endpoint: "/api/api-key/v1/rotate/:id",
		docSlug: "post-api-api-key-v1rotate-by-api_key_id",
	},
	{
		id: "enable",
		label: "Enable Key",
		method: "POST",
		endpoint: "/api/api-key/v1/enable/:id",
		docSlug: "post-api-api-key-v1enable-by-api_key_id",
	},
	{
		id: "disable",
		label: "Disable Key",
		method: "POST",
		endpoint: "/api/api-key/v1/disable/:id",
		docSlug: "post-api-api-key-v1disable-by-api_key_id",
	},
] as const;

export const codeExamples = {
	nodejs: {
		create: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.create({
  name: "Production Key",
});

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.key);`,
		list: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKeys, apiKeyError } = await reloop.apiKey.list({
  page: 1,
  limit: 10,
  enabled: true,
});

if (apiKeyError) throw apiKeyError;

console.log(apiKeys.total, apiKeys.apiKeys);`,
		get: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.get("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.name, apiKey.enabled);`,
		update: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.update("key_123456789", {
  name: "Updated Key Name",
});

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.name);`,
		delete: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.delete("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.message);`,
		rotate: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.rotate("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.key);`,
		enable: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.enable("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.enabled);`,
		disable: `import { Reloop } from "reloop-email";

const reloop = new Reloop({ apiKey: "rl_123456789" });

const { apiKey, apiKeyError } = await reloop.apiKey.disable("key_123456789");

if (apiKeyError) throw apiKeyError;

console.log(apiKey.id, apiKey.enabled);`,
	},
	python: {
		create: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.create({
  "name": "Production Key",
})

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["key"])`,
		list: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.list({
  "page": 1,
  "limit": 10,
  "enabled": True,
})

if result.api_key_error:
    raise result.api_key_error

print(result.api_keys["total"], result.api_keys["apiKeys"])`,
		get: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.get("key_123456789")

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["name"], result.api_key["enabled"])`,
		update: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.update("key_123456789", {
  "name": "Updated Key Name",
})

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["name"])`,
		delete: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.delete("key_123456789")

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["message"])`,
		rotate: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.rotate("key_123456789")

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["key"])`,
		enable: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.enable("key_123456789")

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["enabled"])`,
		disable: `from reloop_email import Reloop

reloop = Reloop(api_key="rl_123456789")

result = reloop.api_key.disable("key_123456789")

if result.api_key_error:
    raise result.api_key_error

print(result.api_key["id"], result.api_key["enabled"])`,
	},
	php: {
		create: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->create([
    'name' => 'Production Key',
]);
echo $apiKey['id'] . ' ' . $apiKey['key'] . PHP_EOL;`,
		list: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKeys = $reloop->apiKey->list([
    'page' => 1,
    'limit' => 10,
    'enabled' => true,
]);
echo $apiKeys['total'] . ' ' . $apiKeys['apiKeys'] . PHP_EOL;`,
		get: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->get('key_123456789');
echo $apiKey['id'] . ' ' . $apiKey['name'] . ' ' . $apiKey['enabled'] . PHP_EOL;`,
		update: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->update('key_123456789', [
    'name' => 'Updated Key Name',
]);
echo $apiKey['id'] . ' ' . $apiKey['name'] . PHP_EOL;`,
		delete: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->delete('key_123456789');
echo $apiKey['id'] . ' ' . $apiKey['message'] . PHP_EOL;`,
		rotate: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->rotate('key_123456789');
echo $apiKey['id'] . ' ' . $apiKey['key'] . PHP_EOL;`,
		enable: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->enable('key_123456789');
echo $apiKey['id'] . ' ' . $apiKey['enabled'] . PHP_EOL;`,
		disable: `<?php

require 'vendor/autoload.php';

use Reloop\\Reloop;

$reloop = Reloop::client('rl_123456789');

$apiKey = $reloop->apiKey->disable('key_123456789');
echo $apiKey['id'] . ' ' . $apiKey['enabled'] . PHP_EOL;`,
	},
	java: {
		create: `import sh.reloop.ReloopClient;
ReloopClient reloop = new ReloopClient("rl_123456789");

CreateApiKeyParams params = new CreateApiKeyParams();
params.name = "Production Key";
var apiKey = reloop.apiKey.create(params);
System.out.println(apiKey.id + " " + apiKey.key);`,
		list: `import sh.reloop.ReloopClient;
ReloopClient reloop = new ReloopClient("rl_123456789");

ApiKeyListParams params = new ApiKeyListParams();
params.page = 1;
params.limit = 10;
params.enabled = true;
var apiKeys = reloop.apiKey.list(params);
System.out.println(apiKeys.total + " " + apiKeys.apiKeys);`,
		get: `import sh.reloop.ReloopClient;

ReloopClient reloop = new ReloopClient("rl_123456789");

var apiKey = reloop.apiKey.get("key_123456789");
System.out.println(apiKey.id + " " + apiKey.name + " " + apiKey.enabled);`,
		update: `import sh.reloop.ReloopClient;
ReloopClient reloop = new ReloopClient("rl_123456789");

UpdateApiKeyParams params = new UpdateApiKeyParams();
params.name = "Updated Key Name";
var apiKey = reloop.apiKey.update("key_123456789", params);
System.out.println(apiKey.id + " " + apiKey.name);`,
		delete: `import sh.reloop.ReloopClient;

ReloopClient reloop = new ReloopClient("rl_123456789");

var apiKey = reloop.apiKey.delete("key_123456789");
System.out.println(apiKey.id + " " + apiKey.message);`,
		rotate: `import sh.reloop.ReloopClient;

ReloopClient reloop = new ReloopClient("rl_123456789");

var apiKey = reloop.apiKey.rotate("key_123456789");
System.out.println(apiKey.id + " " + apiKey.key);`,
		enable: `import sh.reloop.ReloopClient;

ReloopClient reloop = new ReloopClient("rl_123456789");

var apiKey = reloop.apiKey.enable("key_123456789");
System.out.println(apiKey.id + " " + apiKey.enabled);`,
		disable: `import sh.reloop.ReloopClient;

ReloopClient reloop = new ReloopClient("rl_123456789");

var apiKey = reloop.apiKey.disable("key_123456789");
System.out.println(apiKey.id + " " + apiKey.enabled);`,
	},
};
