export type DnsblCategory = "reputation" | "spam" | "malware" | "domain";
export type DnsblImpact = "high" | "medium" | "low";
export type DnsblListType = "ip" | "domain";

export interface DnsblProvider {
	id: string;
	name: string;
	host: string;
	listType: DnsblListType;
	category: DnsblCategory;
	impact: DnsblImpact;
	supportsIpv4: boolean;
	supportsIpv6: boolean;
	delistUrl: string;
	description: string;
}

/**
 * Catalog of active, responsive email-relevant public DNSBLs.
 * Dead, decommissioned, and commercial-only private zones have been pruned.
 * Keep frontend `content.ts` in sync with this catalog.
 */
export const IP_DNSBL_PROVIDERS: DnsblProvider[] = [
	{
		id: "spamhaus-zen",
		name: "Spamhaus ZEN",
		host: "zen.spamhaus.org",
		listType: "ip",
		category: "reputation",
		impact: "high",
		supportsIpv4: true,
		supportsIpv6: true,
		delistUrl: "https://check.spamhaus.org",
		description:
			"Combined SBL, CSS, XBL, and PBL. The most widely used IP DNSBL. Public resolvers are refused; a failed query is inconclusive, not clean.",
	},
	{
		id: "barracuda",
		name: "Barracuda BRBL",
		host: "b.barracudacentral.org",
		listType: "ip",
		category: "spam",
		impact: "high",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.barracudacentral.org/rbl/removal-request",
		description:
			"Barracuda Reputation Block List. Unregistered resolver IPs may receive empty replies; treat those as inconclusive, not a pass.",
	},
	{
		id: "spamcop",
		name: "SpamCop SCBL",
		host: "bl.spamcop.net",
		listType: "ip",
		category: "spam",
		impact: "high",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.spamcop.net/bl.shtml",
		description:
			"Automated listings from SpamCop user reports. Entries usually expire on their own.",
	},
	{
		id: "psbl",
		name: "PSBL (Surriel)",
		host: "psbl.surriel.com",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://psbl.surriel.com/remove",
		description: "Passive Spam Block List of confirmed spam sources.",
	},
	{
		id: "mailspike-bl",
		name: "Mailspike BL",
		host: "bl.mailspike.net",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://mailspike.org/iplookup.html",
		description:
			"Mailspike zero-hour IP blocklist.",
	},
	{
		id: "mailspike-z",
		name: "Mailspike Z",
		host: "z.mailspike.net",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://mailspike.org/iplookup.html",
		description:
			"Mailspike zero-hour real-time sender reputation zone.",
	},
	{
		id: "hostkarma",
		name: "HostKarma Blacklist",
		host: "hostkarma.junkemailfilter.com",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://wiki.junkemailfilter.com/index.php/Hostkarma",
		description:
			"HostKarma IP reputation. 127.0.0.1 is a whitelist (not listed); 127.0.0.2–4 are listings.",
	},
	{
		id: "gbudb-truncate",
		name: "GBUdb Truncate",
		host: "truncate.gbudb.net",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.gbudb.com/truncate",
		description: "Statistical IP reputation zone used by mail filters.",
	},
	{
		id: "spamrats-all",
		name: "SpamRATS! All",
		host: "all.spamrats.com",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.spamrats.com/lookup.php",
		description: "SpamRATS combined spam and auth-attack zone.",
	},
	{
		id: "rats-dyna",
		name: "SpamRATS! Dyna",
		host: "dyna.spamrats.com",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.spamrats.com/lookup.php",
		description: "Dynamic IP address space and residential connections.",
	},
	{
		id: "rats-noptr",
		name: "SpamRATS! NoPtr",
		host: "noptr.spamrats.com",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.spamrats.com/lookup.php",
		description: "IP addresses with missing or invalid reverse DNS (PTR) records.",
	},
	{
		id: "sem-black",
		name: "Spam Eating Monkey Black",
		host: "bl.spameatingmonkey.net",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://spameatingmonkey.com/lookup",
		description: "Listings from trap-mailbox hits.",
	},
	{
		id: "sem-backscatter",
		name: "Spam Eating Monkey Backscatter",
		host: "backscatter.spameatingmonkey.net",
		listType: "ip",
		category: "reputation",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://spameatingmonkey.com/lookup",
		description: "IPs sending misdirected non-delivery reports (NDRs / backscatter).",
	},
	{
		id: "nordspam",
		name: "NordSpam",
		host: "bl.nordspam.com",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.nordspam.com/delisting",
		description: "Nordic spam DNSBL.",
	},
	{
		id: "blocklist-de",
		name: "Blocklist.de",
		host: "bl.blocklist.de",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.blocklist.de/en/search.html",
		description: "Community-driven list of IPs attacking mail servers and web services.",
	},
	{
		id: "dronebl",
		name: "DroneBL",
		host: "dnsbl.dronebl.org",
		listType: "ip",
		category: "malware",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://dronebl.org/lookup",
		description: "Real-time tracking of botnets, compromised routers, open relays, and proxies.",
	},
	{
		id: "dan-tor",
		name: "Dan.me.uk Tor List",
		host: "tor.dan.me.uk",
		listType: "ip",
		category: "reputation",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.dan.me.uk/torlist",
		description: "All active Tor network node IP addresses.",
	},
	{
		id: "dan-torexit",
		name: "Dan.me.uk Tor Exit List",
		host: "torexit.dan.me.uk",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.dan.me.uk/torlist",
		description: "Active Tor exit nodes that can originate outbound mail or web traffic.",
	},
	{
		id: "cymru-bogons",
		name: "Team Cymru Bogons",
		host: "bogons.cymru.com",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://www.team-cymru.com/bogon-reference",
		description: "Unallocated and reserved IP address space that should not send public traffic.",
	},
	{
		id: "fabelsources",
		name: "Fabel.dk Spam Sources",
		host: "spamsources.fabel.dk",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.fabel.dk",
		description: "Danish spam source IP list.",
	},
	{
		id: "imp-spam",
		name: "IMP SPAM",
		host: "spam.pedantic.org",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://pedantic.org",
		description: "IMP / Pedantic spam source DNSBL.",
	},
	{
		id: "interserver",
		name: "InterServer RBL",
		host: "rbl.interserver.net",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://rbl.interserver.net",
		description: "InterServer hosting provider public spam DNSBL.",
	},
	{
		id: "nosolicitado",
		name: "NoSolicitado DNSBL",
		host: "bl.nosolicitado.org",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://nosolicitado.org",
		description: "Spanish community spam source DNSBL.",
	},
	{
		id: "rbl-jp",
		name: "RBL JP",
		host: "all.rbl.jp",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.rbl.jp",
		description: "Japanese DNSBL targeting Asian spam sources.",
	},
	{
		id: "s5h",
		name: "s5h.net All",
		host: "all.s5h.net",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.s5h.net",
		description: "Dynamic IP and spam source tracking DNSBL.",
	},
	{
		id: "schulte",
		name: "Schulte RBL",
		host: "rbl.schulte.org",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://rbl.schulte.org",
		description: "German private real-time blackhole list.",
	},
	{
		id: "senderscore",
		name: "Sender Score Reputation Network",
		host: "bl.score.senderscore.com",
		listType: "ip",
		category: "reputation",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://senderscore.org",
		description: "Validity Sender Score IP reputation network blocklist.",
	},
	{
		id: "suomispam",
		name: "Suomispam Reputation",
		host: "bl.suomispam.net",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://suomispam.net",
		description: "Finnish spam DNSBL and reputation scoring list.",
	},
	{
		id: "uceprotect-1",
		name: "UCEPROTECT Level 1",
		host: "dnsbl-1.uceprotect.net",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.uceprotect.net/en/index.php?m=7",
		description:
			"Level 1 lists individual spam source IPs. Many receivers ignore it due to false positives.",
	},
	{
		id: "uceprotect-2",
		name: "UCEPROTECT Level 2",
		host: "dnsbl-2.uceprotect.net",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.uceprotect.net/en/index.php?m=7",
		description:
			"Level 2 lists entire subnets/allocations with multiple spam sources.",
	},
	{
		id: "zapbl",
		name: "ZapBL",
		host: "dnsbl.zapbl.net",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://zapbl.net",
		description: "Fast-response spam and compromised server DNSBL.",
	},
	{
		id: "zero-spam",
		name: "0Spam Project",
		host: "0spam.fusionzero.com",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://0spam.org",
		description: "Community-run spam source DNSBL.",
	},
	{
		id: "zero-spam-rbl",
		name: "0Spam RBL",
		host: "0spam-nignore.fusionzero.com",
		listType: "ip",
		category: "spam",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://0spam.org",
		description: "0Spam real-time blackhole list without ignore lists.",
	},
	{
		id: "backscatterer",
		name: "Backscatterer",
		host: "ips.backscatterer.org",
		listType: "ip",
		category: "reputation",
		impact: "low",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "http://www.backscatterer.org/?target=removal",
		description:
			"IPs sending misdirected bounces (backscatter), not a general spam-source list.",
	},
	{
		id: "spfbl",
		name: "SPFBL",
		host: "dnsbl.spfbl.net",
		listType: "ip",
		category: "spam",
		impact: "medium",
		supportsIpv4: true,
		supportsIpv6: false,
		delistUrl: "https://spfbl.net",
		description:
			"Public spam DNSBL used especially in Latin America. Query is the sending IP, not a website.",
	},
];

export const DOMAIN_DNSBL_PROVIDERS: DnsblProvider[] = [
	{
		id: "spamhaus-dbl",
		name: "Spamhaus DBL",
		host: "dbl.spamhaus.org",
		listType: "domain",
		category: "domain",
		impact: "high",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://check.spamhaus.org",
		description:
			"Spamhaus Domain Block List. Query is the domain name, not an IP.",
	},
	{
		id: "uribl-multi",
		name: "URIBL Multi",
		host: "multi.uribl.com",
		listType: "domain",
		category: "domain",
		impact: "high",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://uribl.com",
		description:
			"URI blocklist of domains seen in spam message bodies and links.",
	},
	{
		id: "surbl-multi",
		name: "SURBL Multi",
		host: "multi.surbl.org",
		listType: "domain",
		category: "domain",
		impact: "high",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://www.surbl.org",
		description:
			"SURBL combined URI list of domains found in unsolicited mail.",
	},
	{
		id: "sem-uribl",
		name: "Spam Eating Monkey URIBL",
		host: "uribl.spameatingmonkey.net",
		listType: "domain",
		category: "domain",
		impact: "medium",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://spameatingmonkey.com/lookup",
		description:
			"SEM URI blocklist of domains seen in spam bodies and links.",
	},
	{
		id: "sem-fresh",
		name: "Spam Eating Monkey Fresh",
		host: "fresh.spameatingmonkey.net",
		listType: "domain",
		category: "domain",
		impact: "medium",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://spameatingmonkey.com/lookup",
		description:
			"SEM list of newly registered domains (less than 5 days old).",
	},
	{
		id: "sem-urired",
		name: "Spam Eating Monkey URIRED",
		host: "urired.spameatingmonkey.net",
		listType: "domain",
		category: "domain",
		impact: "medium",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://spameatingmonkey.com/lookup",
		description:
			"SEM blocklist of open redirector domains seen in spam bodies.",
	},
	{
		id: "nordspam-dbl",
		name: "NordSpam DBL",
		host: "dbl.nordspam.com",
		listType: "domain",
		category: "domain",
		impact: "medium",
		supportsIpv4: false,
		supportsIpv6: false,
		delistUrl: "https://www.nordspam.com/delisting",
		description:
			"NordSpam domain blocklist. Queried by domain name, companion to NordSpam IP list.",
	},
];

export const DNSBL_PROVIDERS: DnsblProvider[] = [
	...IP_DNSBL_PROVIDERS,
	...DOMAIN_DNSBL_PROVIDERS,
];

export const IP_DNSBL_COUNT = IP_DNSBL_PROVIDERS.length;
export const DOMAIN_DNSBL_COUNT = DOMAIN_DNSBL_PROVIDERS.length;
export const DNSBL_COUNT = DNSBL_PROVIDERS.length;
