#!/bin/bash
set -e

# Change to the directory of this script so relative paths work accurately
cd "$(dirname "$0")"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}Welcome to Reloop Production Deployment Script${NC}"

# 1. Check prerequisites
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Docker is not installed. Please install Docker and try again.${NC}"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}Docker Compose is not installed. Please install Docker Compose and try again.${NC}"
    exit 1
fi

# 2. Prompt for Domain
if [ -z "$DOMAIN" ]; then
    read -p "Enter your primary domain (e.g., reloop.sh): " DOMAIN
fi

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Domain is required.${NC}"
    exit 1
fi

# 3. Setup .env file
if [ ! -f .env ]; then
    echo -e "${BLUE}Creating .env file...${NC}"
    # Generate random passwords if not set
    DB_PASS=$(openssl rand -hex 16)
    REDIS_PASS=$(openssl rand -hex 16)
    CH_PASS=$(openssl rand -hex 16)
    BETTER_AUTH_SECRET=$(openssl rand -base64 32)

    cat <<EOF > .env
# Auto-generated by deploy.sh
DOMAIN=$DOMAIN
DOCKERHUB_USERNAME=reloopsh
NODE_ENV=production

# Database Setup
POSTGRES_USER=reloop
POSTGRES_PASSWORD=$DB_PASS
POSTGRES_DB=reloop
DATABASE_URL=postgresql://reloop:$DB_PASS@reloop-postgres:5432/reloop

REDIS_PASSWORD=$REDIS_PASS
REDIS_URL=redis://:default@reloop-redis:6379

CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=$CH_PASS
CLICKHOUSE_DB=reloop
CLICKHOUSE_URL=http://reloop-clickhouse:8123

# App specific
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
NEXT_PUBLIC_APP_URL=https://$DOMAIN
EOF
    echo -e "${GREEN}.env file created with generated credentials.${NC}"
else
    echo -e "${BLUE}.env file already exists. Ensuring DOMAIN is set...${NC}"
    if ! grep -q "^DOMAIN=" .env; then
        echo "DOMAIN=$DOMAIN" >> .env
    else
        # Replace existing DOMAIN value
        sed -i.bak "s/^DOMAIN=.*/DOMAIN=$DOMAIN/" .env
    fi
fi

# Export domain to make it available to the docker compose command
export DOMAIN=$DOMAIN
export DOCKERHUB_USERNAME=reloopsh

# 4. Pull images and run docker-compose
echo -e "${BLUE}Pulling images and starting Docker Compose stack...${NC}"
docker compose -f docker-compose.prod.yml pull
docker compose -f docker-compose.prod.yml up -d

# Wait for postgres to be healthy
echo -e "${BLUE}Waiting for PostgreSQL to be ready...${NC}"
sleep 10 # Basic wait, healthcheck in docker will also handle it.

# 5. Run database migrations
echo -e "${BLUE}Running database migrations...${NC}"
# Use a one-off bun container on the same network to run migrations
# We use the existing codebase to run db migration script
docker run --rm --network reloop-network \
  -v $(pwd)/..:/app -w /app \
  --env-file .env \
  oven/bun:alpine bun run db:migrate

echo -e "${GREEN}Deployment Complete!${NC}"
echo -e "Your application should soon be available at ${BLUE}https://$DOMAIN${NC}"
