export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	WEBHOOK_ALREADY_EXISTS: "WEBHOOK_ALREADY_EXISTS",
	WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",
	WEBHOOK_INVALID_URL: "WEBHOOK_INVALID_URL",
	WEBHOOK_UNAUTHORIZED: "WEBHOOK_UNAUTHORIZED",
	DATABASE_ERROR: "DATABASE_ERROR",
} as const;
