#!/usr/bin/env bun
/**
 * Fully generate dashboard API Keys drawer config from @reloop/code-samples.
 *
 * Discovers every api-key sample module — no hand-maintained op list.
 * Emits languages, operations, and codeExamples.
 *
 *   bun run sync:sdk-samples
 *   bun run sync:sdk-samples:check
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
	escapeTemplateLiteral,
	extractSamples,
	findSampleFiles,
	folderToOpKey,
	loadDocSlugIndex,
	opKeyToLabel,
	parseCurlMeta,
	resolveDocSlug,
	sampleById,
} from "./lib/extract-x-code-samples";

const REPO_ROOT = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const API_KEY_SAMPLES = path.join(
	REPO_ROOT,
	"packages/code-samples/src/api-key",
);
const DOCS_DIR = path.join(
	REPO_ROOT,
	"apps/frontend/docs/content/docs/api/api-key",
);
const OUT_FILE = path.join(
	REPO_ROOT,
	"apps/frontend/dashboard/src/components/api-details/api-keys-code-examples.ts",
);

const CHECK = process.argv.includes("--check");

/** Sample id → dashboard language config */
const LANG_MAP: Record<
	string,
	{ langKey: string; label: string; shikiLang: string }
> = {
	node: { langKey: "nodejs", label: "Node", shikiLang: "javascript" },
	python: { langKey: "python", label: "Python", shikiLang: "python" },
	php: { langKey: "php", label: "PHP", shikiLang: "php" },
	java: { langKey: "java", label: "Java", shikiLang: "java" },
};

const DASHBOARD_LANG_ORDER = ["node", "python", "php", "java"] as const;

type OpMeta = {
	id: string;
	label: string;
	method: string;
	endpoint: string;
	docSlug?: string;
	folder: string;
	samples: ReturnType<typeof extractSamples>;
};

function discoverOps(): OpMeta[] {
	const docSlugs = loadDocSlugIndex(DOCS_DIR);
	const files = findSampleFiles(API_KEY_SAMPLES).sort();

	const ops: OpMeta[] = [];

	for (const file of files) {
		const folder = path.basename(path.dirname(file));
		const samples = extractSamples(file);
		if (samples.length === 0) continue;

		const curl = sampleById(samples, "curl");
		if (!curl) {
			throw new Error(`Missing curl sample in ${folder}`);
		}

		const { method, endpoint } = parseCurlMeta(curl.source);
		const id = folderToOpKey(folder);
		const docSlug = resolveDocSlug(docSlugs, method, endpoint);

		ops.push({
			id,
			label: opKeyToLabel(id),
			method,
			endpoint,
			docSlug,
			folder,
			samples,
		});
	}

	if (ops.length === 0) {
		throw new Error(`No api-key samples found under ${API_KEY_SAMPLES}`);
	}

	// Stable product order: create first, then list, rest alpha by id
	const preferred = [
		"create",
		"list",
		"get",
		"update",
		"delete",
		"rotate",
		"enable",
		"disable",
	];
	ops.sort((a, b) => {
		const ai = preferred.indexOf(a.id);
		const bi = preferred.indexOf(b.id);
		if (ai === -1 && bi === -1) return a.id.localeCompare(b.id);
		if (ai === -1) return 1;
		if (bi === -1) return -1;
		return ai - bi;
	});

	return ops;
}

function buildFile(ops: OpMeta[]): string {
	const langKeysUsed: string[] = [];
	for (const sampleId of DASHBOARD_LANG_ORDER) {
		if (LANG_MAP[sampleId]) langKeysUsed.push(sampleId);
	}

	const byLang: Record<string, Record<string, string>> = {};
	for (const sampleId of langKeysUsed) {
		byLang[LANG_MAP[sampleId]!.langKey] = {};
	}

	for (const op of ops) {
		for (const sampleId of langKeysUsed) {
			const { langKey } = LANG_MAP[sampleId]!;
			const sample = sampleById(op.samples, sampleId);
			if (!sample) {
				throw new Error(
					`Missing sample id="${sampleId}" for api-key op "${op.folder}"`,
				);
			}
			byLang[langKey]![op.id] = sample.source.trimEnd();
		}
	}

	const lines: string[] = [
		"// AUTO-GENERATED by scripts/sync-dashboard-api-key-samples.ts",
		"// Do not edit by hand.",
		"// Canonical source: packages/code-samples (@reloop/code-samples)",
		"// Regenerate: bun run sync:sdk-samples",
		"",
		"export const languages = [",
	];

	for (const sampleId of langKeysUsed) {
		const lang = LANG_MAP[sampleId]!;
		lines.push(
			`\t{ id: "${lang.langKey}", label: "${lang.label}", shikiLang: "${lang.shikiLang}" },`,
		);
	}
	lines.push("] as const;");
	lines.push("");
	lines.push("export const operations = [");

	for (const op of ops) {
		const doc = op.docSlug ? `,\n\t\tdocSlug: "${op.docSlug}"` : "";
		lines.push("\t{");
		lines.push(`\t\tid: "${op.id}",`);
		lines.push(`\t\tlabel: "${op.label}",`);
		lines.push(`\t\tmethod: "${op.method}",`);
		lines.push(`\t\tendpoint: "${op.endpoint}"${doc},`);
		lines.push("\t},");
	}
	lines.push("] as const;");
	lines.push("");
	lines.push("export const codeExamples = {");

	for (const sampleId of langKeysUsed) {
		const { langKey } = LANG_MAP[sampleId]!;
		lines.push(`\t${langKey}: {`);
		for (const op of ops) {
			const source = byLang[langKey]![op.id]!;
			lines.push(`\t\t${op.id}: \`${escapeTemplateLiteral(source)}\`,`);
		}
		lines.push("\t},");
	}

	lines.push("};");
	lines.push("");
	return lines.join("\n");
}

const ops = discoverOps();
const next = buildFile(ops);
const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : "";

if (CHECK) {
	if (prev !== next) {
		console.error(
			"Dashboard api-keys-code-examples.ts is out of date with backend x-codeSamples.\n" +
				"Run: bun run sync:sdk-samples",
		);
		process.exit(1);
	}
	console.log(
		`OK: dashboard api-key samples match @reloop/code-samples (${ops.length} ops).`,
	);
	process.exit(0);
}

if (prev === next) {
	console.log(
		`Dashboard api-key samples already up to date (${ops.length} ops).`,
	);
	process.exit(0);
}

fs.writeFileSync(OUT_FILE, next);
console.log(
	`Updated ${path.relative(REPO_ROOT, OUT_FILE)} (${ops.length} ops: ${ops.map((o) => o.id).join(", ")})`,
);
