#!/usr/bin/env bun
/**
 * Generate dashboard API Keys code examples from backend x-codeSamples.
 *
 * Canonical source: apps/backend/api-key route x-codeSamples.ts files
 * Output: apps/frontend/dashboard/src/components/api-details/api-keys-code-examples.ts
 *
 *   bun run sync:sdk-samples
 *   bun run scripts/sync-dashboard-api-key-samples.ts --check
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
	escapeTemplateLiteral,
	extractSamples,
	findSampleFiles,
	sampleById,
} from "./lib/extract-x-code-samples";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const API_KEY_ROUTES = path.join(
	REPO_ROOT,
	"apps/backend/api-key/src/routes/api-key",
);
const OUT_FILE = path.join(
	REPO_ROOT,
	"apps/frontend/dashboard/src/components/api-details/api-keys-code-examples.ts",
);

const CHECK = process.argv.includes("--check");

const OPS = [
	{ folder: "create-api-key", key: "create" },
	{ folder: "list-api-keys", key: "list" },
	{ folder: "get-api-key", key: "get" },
	{ folder: "update-api-key", key: "update" },
	{ folder: "delete-api-key", key: "delete" },
	{ folder: "rotate-api-key", key: "rotate" },
	{ folder: "enable-api-key", key: "enable" },
	{ folder: "disable-api-key", key: "disable" },
] as const;

const LANGS = [
	{ sampleId: "node", langKey: "nodejs" },
	{ sampleId: "python", langKey: "python" },
	{ sampleId: "php", langKey: "php" },
] as const;

function loadOpSamples(folder: string) {
	const dir = path.join(API_KEY_ROUTES, folder);
	const files = findSampleFiles(dir);
	if (files.length === 0) {
		throw new Error(`No x-codeSamples under ${dir}`);
	}
	return extractSamples(files[0]!);
}

function buildFile(): string {
	const byLang: Record<string, Record<string, string>> = {
		nodejs: {},
		python: {},
		php: {},
	};

	for (const op of OPS) {
		const samples = loadOpSamples(op.folder);
		for (const { sampleId, langKey } of LANGS) {
			const sample = sampleById(samples, sampleId);
			if (!sample) {
				throw new Error(
					`Missing sample id="${sampleId}" for api-key op "${op.folder}"`,
				);
			}
			byLang[langKey]![op.key] = sample.source.trimEnd();
		}
	}

	const lines: string[] = [
		"// AUTO-GENERATED by scripts/sync-dashboard-api-key-samples.ts",
		"// Do not edit by hand.",
		"// Canonical source: apps/backend/api-key route x-codeSamples.ts files",
		"// Regenerate: bun run sync:sdk-samples",
		"",
		"export const codeExamples = {",
	];

	for (const { langKey } of LANGS) {
		lines.push(`\t${langKey}: {`);
		for (const op of OPS) {
			const source = byLang[langKey]![op.key]!;
			lines.push(`\t\t${op.key}: \`${escapeTemplateLiteral(source)}\`,`);
		}
		lines.push("\t},");
	}

	lines.push("};");
	lines.push("");
	return lines.join("\n");
}

const next = buildFile();
const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : "";

if (CHECK) {
	if (prev !== next) {
		console.error(
			"Dashboard api-keys-code-examples.ts is out of date with backend x-codeSamples.\n" +
				"Run: bun run sync:sdk-samples",
		);
		process.exit(1);
	}
	console.log("OK: dashboard api-key samples match backend x-codeSamples.");
	process.exit(0);
}

if (prev === next) {
	console.log("Dashboard api-key samples already up to date.");
	process.exit(0);
}

fs.writeFileSync(OUT_FILE, next);
console.log(`Updated ${path.relative(REPO_ROOT, OUT_FILE)}`);
