import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@dashboard/components/footer";
import { Navbar } from "@dashboard/components/navbar";
import { CreateOrganizationModal } from "@dashboard/components/organization/create-organization";
import SWRProvider from "@dashboard/providers/swr.config";
import { IconsSprite } from "@reloop/ui/components/icon";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={"bg-bg-white-0 text-text-strong-950 antialiased"}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<SWRProvider>
						<Navbar />
						{children}
						<IconsSprite />
						<Footer />
						<CreateOrganizationModal />
					</SWRProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
