export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	DOMAIN_ALREADY_EXISTS: "DOMAIN_ALREADY_EXISTS",
	DOMAIN_NOT_FOUND: "DOMAIN_NOT_FOUND",
	DOMAIN_INVALID: "DOMAIN_INVALID",
	DOMAIN_FAILED_TO_UNDELETE: "DOMAIN_FAILED_TO_UNDELETE",
	DOMAIN_VERIFICATION_FAILED: "DOMAIN_VERIFICATION_FAILED",
	DATABASE_ERROR: "DATABASE_ERROR",
} as const;
